// Copyright (c) Microsoft Corporation
// License: MIT OR Apache-2.0

//! PDB CodeView annotation injection for WPP trace metadata.
//!
//! This module patches PDB files by injecting `S_ANNOTATION` CodeView symbol
//! records into a DBI module's symbol stream (debug$S).  This matches the
//! format that C WPP (`tracewpp`) uses, enabling standard tools like
//! `tracefmt.exe`, TraceView, WPA, and `!rcdrkd` to decode trace events.
//!
//! ## Strategy
//!
//! The `atexit` handler in `manifest.rs` calls into this module after the
//! linker has produced the PDB.  It:
//!
//! 1. Builds binary `S_ANNOTATION` records from trace metadata (C WPP TMF
//!    format).
//! 2. Opens the PDB with `ms-pdb` using `Pdb::modify`.
//! 3. Creates (or updates) a dedicated `wpp_annotations` DBI module whose
//!    symbol stream contains the `S_ANNOTATION` records.
//! 4. Updates the DBI stream to include the new module entry and adjusts the
//!    File Info Substream so the module count stays consistent.
//!
//! This places the annotations exactly where WPP decoder tools expect them:
//! in the module symbol substream of a DBI module entry, identical to how
//! `link.exe` processes `wpp_annotations.obj` files generated by `tracewpp`.

use crate::manifest::TraceManifestEntry;

// ---- Constants ---------------------------------------------------------------

/// CodeView symbol kind for `S_ANNOTATION` (0x1019).
const S_ANNOTATION_KIND: u16 = 0x1019;

/// CodeView C13 signature (magic number at start of every module stream).
const CV_SIGNATURE_C13: u32 = 4;

/// MSF stream index for the DBI stream.
const DBI_STREAM_INDEX: u32 = 3;

/// Size of the DBI stream header (`DbiStreamHeader`) in bytes.
const DBI_HEADER_SIZE: usize = 64;

// DBI header field offsets (all `I32<LE>` unless otherwise noted)
/// Offset of `mod_info_size` within the DBI header.
const DBI_MOD_INFO_SIZE_OFFSET: usize = 24;
/// Offset of `section_contribution_size` within the DBI header.
const DBI_SC_SIZE_OFFSET: usize = 28;
/// Offset of `section_map_size` within the DBI header.
const DBI_SM_SIZE_OFFSET: usize = 32;
/// Offset of `source_info_size` within the DBI header.
const DBI_SOURCE_INFO_SIZE_OFFSET: usize = 36;

// `ModuleInfoFixed` field offsets (relative to a single ModInfo entry start).
//
// Layout verified against `ms-pdb` source (`dbi/modules.rs`):
// ```
//   [0..4]   unused1           : U32<LE>
//   [4..32]  section_contrib   : SectionContribEntry (28 bytes)
//   [32..34] flags             : U16<LE>
//   [34..36] stream            : StreamIndexU16
//   [36..40] sym_byte_size     : U32<LE>
//   [40..44] c11_byte_size     : U32<LE>
//   [44..48] c13_byte_size     : U32<LE>
//   [48..50] source_file_count : U16<LE>
//   [50..52] padding           : [u8; 2]
//   [52..56] unused2           : U32<LE>
//   [56..60] source_file_name_index : U32<LE>
//   [60..64] pdb_file_path_name_index : U32<LE>
// ```

/// Offset of `stream` (`StreamIndexU16`) — module symbol stream index.
const MODI_STREAM_OFFSET: usize = 34;
/// Offset of `sym_byte_size` (`U32<LE>`) — symbol substream size (incl. 4-byte
/// CV signature).
const MODI_SYM_SIZE_OFFSET: usize = 36;
/// Size of the fixed-size portion of a `ModuleInfoFixed` struct.
const MODI_FIXED_SIZE: usize = 64;

/// Section index value meaning "no section contribution".
const SC_NO_SECTION: u16 = 0xFFFF;

// ---- Parsed data structures --------------------------------------------------

/// Information parsed from one `ModuleInfoFixed` entry in the DBI module info
/// substream.
struct ParsedModInfo {
    /// Byte offset of this entry within the module info substream.
    offset_in_substream: usize,
    /// Total byte length (fixed + names + alignment padding).
    #[allow(dead_code)]
    total_len: usize,
    /// Stream index of the module's symbol stream (`None` if 0xFFFF).
    stream_index: Option<u32>,
    /// Size of the symbol substream within the module stream (includes 4-byte
    /// CV signature).
    #[allow(dead_code)]
    sym_byte_size: u32,
    /// Module name (UTF-8 lossy).
    module_name: String,
}

// ---- S_ANNOTATION record builder (C WPP TMF style) --------------------------

/// Builds a single `S_ANNOTATION` record matching C WPP `tracewpp` output.
///
/// The annotation strings follow the exact TMF format that `tracefmt`,
/// `traceview`, and `!rcdrkd` expect:
///
/// ```text
/// String 0: "TMF:"
/// String 1: "{GUID} {driver} // SRC={file} MJ= MN="
/// String 2: "#typev {driver}_{line} {msg_id} \"%0{wpp_format}\""
/// String 3: "{"                              (only if args present)
/// String 4+: "{name}, {ItemType} -- {slot}"  (one per argument)
/// String N: "}"                              (only if args present)
/// ```
fn build_annotation_record_wpp(
    control_guid: &str,
    entry: &TraceManifestEntry,
    wpp_format: &str,
    driver_name: &str,
) -> Vec<u8> {
    let mut strings: Vec<String> = Vec::new();

    // String 0: TMF marker
    strings.push("TMF:".to_string());

    // String 1: GUID + driver name + source info
    let src_file = entry
        .source_file
        .rsplit(['/', '\\'])
        .next()
        .unwrap_or(&entry.source_file);
    strings.push(format!(
        "{} {} // SRC={} MJ= MN=",
        control_guid, driver_name, src_file
    ));

    // String 2: #typev declaration
    let func_name = format!("{}_{}", driver_name, entry.line_number);
    strings.push(format!(
        "#typev {} {} \"%0{}\"",
        func_name, entry.message_id, wpp_format
    ));

    // Parameter block (only if arguments exist)
    if !entry.args.is_empty() {
        strings.push("{".to_string());
        for arg in &entry.args {
            strings.push(format!(
                "{}, {} -- {}",
                arg.name, arg.item_type, arg.param_number
            ));
        }
        strings.push("}".to_string());
    }

    // ---- Build the binary record ----
    let mut payload = Vec::new();
    // off (u32): code offset — 0 (unresolved, no anchor symbol)
    payload.extend_from_slice(&0u32.to_le_bytes());
    // seg (u16): segment index — 1 (.text)
    payload.extend_from_slice(&1u16.to_le_bytes());
    // csz (u16): count of NUL-terminated annotation strings
    payload.extend_from_slice(&(strings.len() as u16).to_le_bytes());
    for s in &strings {
        payload.extend_from_slice(s.as_bytes());
        payload.push(0u8); // NUL terminator
    }
    // Pad payload to 4-byte alignment
    while payload.len() % 4 != 0 {
        payload.push(0u8);
    }

    // reclen = sizeof(rectyp) + sizeof(payload)
    let reclen = (2 + payload.len()) as u16;
    let mut record = Vec::new();
    record.extend_from_slice(&reclen.to_le_bytes());
    record.extend_from_slice(&S_ANNOTATION_KIND.to_le_bytes());
    record.extend_from_slice(&payload);
    record
}

// ---- JSON manifest builder ---------------------------------------------------

/// Builds a JSON manifest of all trace annotations for storage in the PDB as a
/// named stream.  This is the human-readable counterpart for debugging.
fn build_json_manifest(
    control_guid: &str,
    entries: &[TraceManifestEntry],
    driver_name: &str,
) -> String {
    let trace_points: Vec<serde_json::Value> = entries
        .iter()
        .map(|e| {
            serde_json::json!({
                "message_id": e.message_id,
                "level": e.level,
                "flag": e.flag,
                "format_string": e.format_string,
                "source_file": e.source_file,
                "line_number": e.line_number,
                "args": e.args.iter().map(|a| {
                    serde_json::json!({
                        "name": a.name,
                        "item_type": a.item_type,
                        "param_number": a.param_number,
                    })
                }).collect::<Vec<_>>(),
            })
        })
        .collect();

    let manifest = serde_json::json!({
        "version": 1,
        "generator": "wdf-macros",
        "driver_name": driver_name,
        "control_guid": control_guid,
        "trace_count": entries.len(),
        "trace_points": trace_points,
    });

    serde_json::to_string_pretty(&manifest).unwrap_or_default()
}

// ---- PDB discovery -----------------------------------------------------------

/// Searches for a recently produced `.pdb` file that matches the driver name
/// in the build output directory tree.
///
/// The scratch directory is at `<target>/…/scratch/…`, so we walk up from
/// there and look for `.pdb` files modified within the last 60 seconds.
pub(crate) fn find_recent_pdb(
    _scratch_dir: &std::path::Path,
    driver_name: &str,
) -> Option<std::path::PathBuf> {
    let search_root;

    if let Ok(target_dir) = std::env::var("CARGO_TARGET_DIR") {
        search_root = std::path::PathBuf::from(target_dir);
    } else if let Ok(manifest_dir) = std::env::var("CARGO_MANIFEST_DIR") {
        let mut dir = std::path::PathBuf::from(manifest_dir);
        loop {
            if dir.join("target").is_dir() {
                search_root = dir.join("target");
                break;
            }
            if !dir.pop() {
                return None;
            }
        }
    } else {
        return None;
    }

    eprintln!(
        "wdf-macros: [pdb_annotation] Searching for PDB matching '{}' under: {}",
        driver_name,
        search_root.display()
    );

    find_newest_pdb_recursive(&search_root, 5, driver_name)
}

fn find_newest_pdb_recursive(
    dir: &std::path::Path,
    max_depth: u32,
    driver_name: &str,
) -> Option<std::path::PathBuf> {
    if max_depth == 0 {
        return None;
    }

    let entries = std::fs::read_dir(dir).ok()?;
    let mut newest: Option<(std::path::PathBuf, std::time::SystemTime)> = None;

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_file() && path.extension().and_then(|e| e.to_str()) == Some("pdb") {
            let stem = path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("");
            if !stem.starts_with(driver_name) {
                continue;
            }
            if let Ok(meta) = std::fs::metadata(&path) {
                if let Ok(modified) = meta.modified() {
                    if let Ok(elapsed) = modified.elapsed() {
                        if elapsed.as_secs() < 60 {
                            match &newest {
                                Some((_, prev_time)) if &modified > prev_time => {
                                    newest = Some((path, modified));
                                }
                                None => {
                                    newest = Some((path, modified));
                                }
                                _ => {}
                            }
                        }
                    }
                }
            }
        } else if path.is_dir() {
            let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if !name.starts_with('.') && name != "build" && name != "incremental" {
                if let Some(found) = find_newest_pdb_recursive(&path, max_depth - 1, driver_name) {
                    if let Ok(meta) = std::fs::metadata(&found) {
                        if let Ok(modified) = meta.modified() {
                            match &newest {
                                Some((_, prev_time)) if &modified > prev_time => {
                                    newest = Some((found, modified));
                                }
                                None => {
                                    newest = Some((found, modified));
                                }
                                _ => {}
                            }
                        }
                    }
                }
            }
        }
    }

    newest.map(|(p, _)| p)
}

// ---- DBI binary helpers ------------------------------------------------------

/// Reads a `u32` from little-endian bytes at `offset`.
fn read_u32_le(data: &[u8], offset: usize) -> u32 {
    u32::from_le_bytes([
        data[offset],
        data[offset + 1],
        data[offset + 2],
        data[offset + 3],
    ])
}

/// Writes a `u32` to little-endian bytes at `offset`.
fn write_u32_le(data: &mut [u8], offset: usize, value: u32) {
    data[offset..offset + 4].copy_from_slice(&value.to_le_bytes());
}

/// Parses `ModuleInfoFixed` entries from the raw Module Info Substream bytes.
///
/// Each entry has a 64-byte fixed header followed by two NUL-terminated strings
/// (module name and object file name), then alignment padding to 4 bytes.
fn parse_mod_info_entries(mod_info_data: &[u8]) -> Vec<ParsedModInfo> {
    let mut entries = Vec::new();
    let mut offset = 0;

    while offset < mod_info_data.len() {
        let entry_start = offset;

        // Need at least the fixed part
        if offset + MODI_FIXED_SIZE > mod_info_data.len() {
            break;
        }

        // stream (U16<LE>) at relative offset 34
        let stream_raw = u16::from_le_bytes([
            mod_info_data[offset + MODI_STREAM_OFFSET],
            mod_info_data[offset + MODI_STREAM_OFFSET + 1],
        ]);
        let stream_index = if stream_raw == 0xFFFF {
            None
        } else {
            Some(u32::from(stream_raw))
        };

        // sym_byte_size (U32<LE>) at relative offset 36
        let sym_byte_size = read_u32_le(mod_info_data, offset + MODI_SYM_SIZE_OFFSET);

        offset += MODI_FIXED_SIZE;

        // Module name (NUL-terminated)
        let name_start = offset;
        while offset < mod_info_data.len() && mod_info_data[offset] != 0 {
            offset += 1;
        }
        let module_name =
            String::from_utf8_lossy(&mod_info_data[name_start..offset]).to_string();
        if offset < mod_info_data.len() {
            offset += 1; // skip NUL
        }

        // Object file name (NUL-terminated)
        while offset < mod_info_data.len() && mod_info_data[offset] != 0 {
            offset += 1;
        }
        if offset < mod_info_data.len() {
            offset += 1; // skip NUL
        }

        // Alignment padding to 4 bytes
        offset = (offset + 3) & !3;

        entries.push(ParsedModInfo {
            offset_in_substream: entry_start,
            total_len: offset - entry_start,
            stream_index,
            sym_byte_size,
            module_name,
        });
    }

    entries
}

/// Builds the raw bytes for a new `ModuleInfoFixed` entry (64-byte fixed header
/// + two NUL-terminated name strings + alignment padding).
fn build_mod_info_bytes(
    stream_index: u16,
    sym_byte_size: u32,
    module_name: &str,
    obj_file_name: &str,
) -> Vec<u8> {
    let mut entry = Vec::with_capacity(128);

    // unused1 (U32<LE>)
    entry.extend_from_slice(&0u32.to_le_bytes());

    // SectionContribEntry (28 bytes):
    //   section(2) + padding1(2) + offset(4) + size(4) + chars(4)
    //   + module_index(2) + padding2(2) + data_crc(4) + reloc_crc(4)
    entry.extend_from_slice(&SC_NO_SECTION.to_le_bytes()); // section = 0xFFFF
    entry.extend_from_slice(&0u16.to_le_bytes()); // padding1
    entry.extend_from_slice(&0i32.to_le_bytes()); // offset
    entry.extend_from_slice(&(-1i32).to_le_bytes()); // size = -1
    entry.extend_from_slice(&0u32.to_le_bytes()); // characteristics
    entry.extend_from_slice(&SC_NO_SECTION.to_le_bytes()); // module_index = 0xFFFF
    entry.extend_from_slice(&0u16.to_le_bytes()); // padding2
    entry.extend_from_slice(&0u32.to_le_bytes()); // data_crc
    entry.extend_from_slice(&0u32.to_le_bytes()); // reloc_crc

    // flags (U16<LE>) — bit 0 = "has been written"
    entry.extend_from_slice(&1u16.to_le_bytes());

    // stream (StreamIndexU16)
    entry.extend_from_slice(&stream_index.to_le_bytes());

    // sym_byte_size (U32<LE>)
    entry.extend_from_slice(&sym_byte_size.to_le_bytes());

    // c11_byte_size (U32<LE>)
    entry.extend_from_slice(&0u32.to_le_bytes());

    // c13_byte_size (U32<LE>)
    entry.extend_from_slice(&0u32.to_le_bytes());

    // source_file_count (U16<LE>)
    entry.extend_from_slice(&0u16.to_le_bytes());

    // padding (2 bytes)
    entry.extend_from_slice(&[0u8; 2]);

    // unused2 (U32<LE>)
    entry.extend_from_slice(&0u32.to_le_bytes());

    // source_file_name_index (U32<LE>)
    entry.extend_from_slice(&0u32.to_le_bytes());

    // pdb_file_path_name_index (U32<LE>)
    entry.extend_from_slice(&0u32.to_le_bytes());

    debug_assert_eq!(
        entry.len(),
        MODI_FIXED_SIZE,
        "ModuleInfoFixed must be 64 bytes"
    );

    // Module name + NUL
    entry.extend_from_slice(module_name.as_bytes());
    entry.push(0);

    // Object file name + NUL
    entry.extend_from_slice(obj_file_name.as_bytes());
    entry.push(0);

    // Pad to 4-byte alignment
    while entry.len() % 4 != 0 {
        entry.push(0);
    }

    entry
}

/// Creates new DBI stream bytes with a new module entry appended to the Module
/// Info Substream and a corresponding entry added to the File Info (Sources)
/// Substream.
///
/// # Layout of the DBI stream
///
/// ```text
/// [ DBI Header               (64 bytes)                              ]
/// [ Module Info Substream     (mod_info_size bytes)                   ]
/// [ Section Contrib Substream (section_contribution_size bytes)       ]
/// [ Section Map Substream     (section_map_size bytes)                ]
/// [ File Info Substream       (source_info_size bytes)                ]
/// [ Type Server Map           (type_server_map_size bytes)            ]
/// [ MFC Type Server Index     (variable)                             ]
/// [ Optional Debug Header     (optional_dbg_header_size bytes)       ]
/// [ EC Substream              (edit_and_continue_size bytes)          ]
/// ```
fn add_module_to_dbi(
    dbi_data: &[u8],
    new_mod_info: &[u8],
    new_module_index: u16,
) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    if dbi_data.len() < DBI_HEADER_SIZE {
        return Err("DBI stream is smaller than header".into());
    }

    // Parse header sizes
    let mod_info_size = read_u32_le(dbi_data, DBI_MOD_INFO_SIZE_OFFSET) as usize;
    let sc_size = read_u32_le(dbi_data, DBI_SC_SIZE_OFFSET) as usize;
    let sm_size = read_u32_le(dbi_data, DBI_SM_SIZE_OFFSET) as usize;
    let source_info_size = read_u32_le(dbi_data, DBI_SOURCE_INFO_SIZE_OFFSET) as usize;

    // Substream boundaries
    let mod_info_end = DBI_HEADER_SIZE + mod_info_size;
    let sc_end = mod_info_end + sc_size;
    let sm_end = sc_end + sm_size;
    let source_info_start = sm_end;
    let source_info_end = source_info_start + source_info_size;

    if source_info_end > dbi_data.len() {
        return Err(format!(
            "DBI substream bounds exceed stream size ({} > {})",
            source_info_end,
            dbi_data.len()
        )
        .into());
    }

    // Build new DBI.  Module Info Substream grows by new_mod_info.len().
    // File Info Substream grows by 4 bytes (+2 module_file_starts, +2
    // module_file_counts).
    let growth = new_mod_info.len() + 4;
    let mut new_dbi = Vec::with_capacity(dbi_data.len() + growth);

    // 1. DBI header (will patch sizes at the end)
    new_dbi.extend_from_slice(&dbi_data[..DBI_HEADER_SIZE]);

    // 2. Module Info Substream: existing + new entry at the end
    new_dbi.extend_from_slice(&dbi_data[DBI_HEADER_SIZE..mod_info_end]);
    new_dbi.extend_from_slice(new_mod_info);

    // 3. Section Contribution + Section Map (unchanged)
    new_dbi.extend_from_slice(&dbi_data[mod_info_end..source_info_start]);

    // 4. File Info (Sources) Substream — insert new module entry
    //
    //    On-disk layout:
    //      u16  num_modules
    //      u16  num_source_files  (may overflow; informational only)
    //      u16  module_file_starts[num_modules]
    //      u16  module_file_counts[num_modules]
    //      u32  file_name_offsets[sum(module_file_counts)]
    //      u8[] names_buffer
    if source_info_size >= 4 {
        let fi = &dbi_data[source_info_start..source_info_end];
        let old_num_modules = u16::from_le_bytes([fi[0], fi[1]]);
        let new_num_modules = old_num_modules + 1;
        let n = old_num_modules as usize;

        // Header: num_modules (u16) + num_source_files (u16)
        new_dbi.extend_from_slice(&new_num_modules.to_le_bytes());
        new_dbi.extend_from_slice(&fi[2..4]); // num_source_files unchanged

        // module_file_starts array: copy existing N entries + append new
        let mfs_end = std::cmp::min(4 + 2 * n, fi.len());
        new_dbi.extend_from_slice(&fi[4..mfs_end]);
        // New module's start offset = total files so far (value doesn't matter
        // for a module with 0 files, but keeps the invariant correct).
        new_dbi.extend_from_slice(&new_module_index.to_le_bytes());

        // module_file_counts array: copy existing N entries + append 0
        let mfc_end = std::cmp::min(mfs_end + 2 * n, fi.len());
        new_dbi.extend_from_slice(&fi[mfs_end..mfc_end]);
        new_dbi.extend_from_slice(&0u16.to_le_bytes()); // 0 files for new module

        // Rest: file_name_offsets + names_buffer (unchanged)
        if mfc_end < fi.len() {
            new_dbi.extend_from_slice(&fi[mfc_end..]);
        }
    } else {
        // File Info Substream absent or too small — copy as-is
        new_dbi.extend_from_slice(&dbi_data[source_info_start..source_info_end]);
    }

    // 5. Everything after File Info Substream
    if source_info_end < dbi_data.len() {
        new_dbi.extend_from_slice(&dbi_data[source_info_end..]);
    }

    // 6. Patch DBI header sizes
    let new_mod_info_size = (mod_info_size + new_mod_info.len()) as u32;
    write_u32_le(&mut new_dbi, DBI_MOD_INFO_SIZE_OFFSET, new_mod_info_size);

    if source_info_size >= 4 {
        let new_source_info_size = (source_info_size + 4) as u32;
        write_u32_le(
            &mut new_dbi,
            DBI_SOURCE_INFO_SIZE_OFFSET,
            new_source_info_size,
        );
    }

    Ok(new_dbi)
}

/// Updates `sym_byte_size` for a module identified by its stream index.
/// Modifies `dbi_data` in place.
fn update_sym_size_in_dbi(
    dbi_data: &mut [u8],
    target_stream_index: u16,
    new_sym_byte_size: u32,
) -> Result<(), Box<dyn std::error::Error>> {
    let mod_info_size = read_u32_le(dbi_data, DBI_MOD_INFO_SIZE_OFFSET) as usize;

    if DBI_HEADER_SIZE + mod_info_size > dbi_data.len() {
        return Err("Module info substream extends past DBI stream".into());
    }

    let mod_info_data = &dbi_data[DBI_HEADER_SIZE..DBI_HEADER_SIZE + mod_info_size];
    let entries = parse_mod_info_entries(mod_info_data);

    for entry in &entries {
        if entry.stream_index == Some(u32::from(target_stream_index)) {
            let abs_offset =
                DBI_HEADER_SIZE + entry.offset_in_substream + MODI_SYM_SIZE_OFFSET;
            write_u32_le(dbi_data, abs_offset, new_sym_byte_size);
            return Ok(());
        }
    }

    Err(format!(
        "Module with stream index {} not found in DBI",
        target_stream_index
    )
    .into())
}

// ---- PDB patching (Windows) --------------------------------------------------

/// Patches the PDB file by injecting `S_ANNOTATION` CodeView records into a
/// dedicated DBI module stream.
///
/// On the first invocation (clean build) this creates a new `wpp_annotations`
/// module.  On subsequent invocations (incremental builds) it locates the
/// existing module and replaces its stream contents.
#[cfg(windows)]
pub(crate) fn patch_pdb_with_annotations(
    pdb_path: &std::path::Path,
    entries: &[TraceManifestEntry],
    control_guid: &str,
    driver_name: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    if entries.is_empty() {
        return Ok(());
    }

    eprintln!(
        "wdf-macros: [pdb_annotation] Patching PDB: {} ({} trace entries)",
        pdb_path.display(),
        entries.len(),
    );

    // ---- Build S_ANNOTATION records in C WPP TMF format ----
    let mut annotation_bytes: Vec<u8> = Vec::new();
    for entry in entries {
        let wpp_fmt = super::manifest::generate_tmf_format_string_pub(
            &entry.format_string,
            &entry.args,
        );
        let record =
            build_annotation_record_wpp(control_guid, entry, &wpp_fmt, driver_name);
        annotation_bytes.extend_from_slice(&record);
    }

    // Module stream layout:
    //   [4: CV_SIGNATURE_C13] [symbols...] [C11 data] [C13 data]
    //   [4: GlobalRefsSize]   [global refs...]
    //
    // sym_byte_size includes the 4-byte CV signature.
    // GlobalRefsSize=0 means no global refs (S_ANNOTATIONREF not created).
    let sym_byte_size = (4 + annotation_bytes.len()) as u32;
    let mut stream_content =
        Vec::with_capacity(sym_byte_size as usize + 4 /* GlobalRefsSize */);
    stream_content.extend_from_slice(&CV_SIGNATURE_C13.to_le_bytes());
    stream_content.extend_from_slice(&annotation_bytes);
    // C11 = 0 bytes, C13 = 0 bytes (nothing to write)
    // GlobalRefsSize = 0
    stream_content.extend_from_slice(&0u32.to_le_bytes());

    // ---- Open PDB in modify mode ----
    let mut pdb = ms_pdb::Pdb::modify(pdb_path).map_err(|e| {
        format!(
            "Failed to open PDB '{}' for modification: {}",
            pdb_path.display(),
            e
        )
    })?;

    let age = pdb.pdbi().age();
    eprintln!(
        "wdf-macros: [pdb_annotation] PDB opened: age={}",
        age,
    );

    // ---- Write JSON manifest as a named stream (for debugging) ----
    let json_manifest = build_json_manifest(control_guid, entries, driver_name);
    pdb.add_or_replace_named_stream(
        "wpp_trace_manifest_json",
        json_manifest.as_bytes(),
    )
    .map_err(|e| format!("Failed to write JSON manifest stream: {e}"))?;

    // Flush PDBI changes (named stream map) to MSF pages
    pdb.flush_all()
        .map_err(|e| format!("Failed to flush PDBI changes: {e}"))?;

    // ---- MSF-level operations for DBI + module stream ----
    let msf = pdb
        .msf_mut_err()
        .map_err(|e| format!("Failed to get MSF writer: {e}"))?;

    // Read the current DBI stream
    let dbi_data = msf
        .read_stream_to_vec(DBI_STREAM_INDEX)
        .map_err(|e| format!("Failed to read DBI stream: {e}"))?;

    if dbi_data.len() < DBI_HEADER_SIZE {
        return Err("DBI stream is smaller than expected header size".into());
    }

    // Parse module info to check if a wpp_annotations module already exists
    let mod_info_size = read_u32_le(&dbi_data, DBI_MOD_INFO_SIZE_OFFSET) as usize;
    let mod_info_end = DBI_HEADER_SIZE + mod_info_size;

    if mod_info_end > dbi_data.len() {
        return Err("Module info substream extends past DBI stream".into());
    }

    let mod_info_data = &dbi_data[DBI_HEADER_SIZE..mod_info_end];
    let mod_entries = parse_mod_info_entries(mod_info_data);
    let wpp_module = mod_entries
        .iter()
        .find(|m| m.module_name.contains("wpp_annotations"));

    if let Some(existing) = wpp_module {
        // ----------------------------------------------------------
        // UPDATE path: replace existing module's stream + sym_size
        // ----------------------------------------------------------
        let stream_idx = existing
            .stream_index
            .ok_or("wpp_annotations module has no stream")?;

        eprintln!(
            "wdf-macros: [pdb_annotation] Updating existing wpp_annotations module (stream {})",
            stream_idx,
        );

        // Replace module stream content
        {
            let mut writer = msf.write_stream(stream_idx).map_err(|e| {
                format!(
                    "Failed to get stream writer for stream {}: {}",
                    stream_idx, e
                )
            })?;
            writer
                .set_contents(&stream_content)
                .map_err(|e| format!("Failed to write module stream: {e}"))?;
        }

        // Update sym_byte_size in the DBI stream
        let mut modified_dbi = dbi_data;
        update_sym_size_in_dbi(
            &mut modified_dbi,
            stream_idx as u16,
            sym_byte_size,
        )?;

        {
            let mut dbi_writer = msf
                .write_stream(DBI_STREAM_INDEX)
                .map_err(|e| format!("Failed to get DBI stream writer: {e}"))?;
            dbi_writer
                .set_contents(&modified_dbi)
                .map_err(|e| format!("Failed to write DBI stream: {e}"))?;
        }
    } else {
        // ----------------------------------------------------------
        // CREATE path: new MSF stream + new DBI module entry
        // ----------------------------------------------------------
        eprintln!("wdf-macros: [pdb_annotation] Creating new wpp_annotations module");

        // Allocate a new MSF stream
        let new_stream_idx = msf
            .new_stream_data(&stream_content)
            .map_err(|e| format!("Failed to create module stream: {e}"))?;

        if new_stream_idx > u32::from(u16::MAX) {
            return Err(format!(
                "New stream index {} exceeds u16 range for module stream",
                new_stream_idx
            )
            .into());
        }

        let module_count = mod_entries.len() as u16;

        // Build the new ModuleInfoFixed entry
        let mod_info_bytes = build_mod_info_bytes(
            new_stream_idx as u16,
            sym_byte_size,
            "wpp_annotations",
            "wpp_annotations",
        );

        // Splice the new module into the DBI stream
        let new_dbi = add_module_to_dbi(&dbi_data, &mod_info_bytes, module_count)?;

        {
            let mut dbi_writer = msf
                .write_stream(DBI_STREAM_INDEX)
                .map_err(|e| format!("Failed to get DBI stream writer: {e}"))?;
            dbi_writer
                .set_contents(&new_dbi)
                .map_err(|e| format!("Failed to write DBI stream: {e}"))?;
        }
    }

    // ---- Commit all MSF changes to disk ----
    msf.commit()
        .map_err(|e| format!("Failed to commit PDB: {e}"))?;

    eprintln!(
        "wdf-macros: [pdb_annotation] PDB patched: {} S_ANNOTATION records ({} bytes) \
         in debug$S module stream",
        entries.len(),
        annotation_bytes.len(),
    );

    Ok(())
}

/// No-op on non-Windows platforms.
#[cfg(not(windows))]
pub(crate) fn patch_pdb_with_annotations(
    _pdb_path: &std::path::Path,
    _entries: &[TraceManifestEntry],
    _control_guid: &str,
    _driver_name: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("wdf-macros: [pdb_annotation] PDB patching is only supported on Windows");
    Ok(())
}
