name: Install LLVM

inputs:
  version:
    description: "LLVM version to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install LLVM ${{ inputs.version }}
      shell: pwsh
      run: |
        if ((Get-WinGetPackage -Id LLVM -Source winget -MatchOption Equals).InstalledVersion -eq '${{ matrix.llvm }}') {
          Write-Host "LLVM ${{ matrix.llvm }} is already installed."
        } else {
          Write-Host "Installing LLVM ${{ matrix.llvm }}..."
          Install-WinGetPackage -Id LLVM.LLVM -Version ${{ matrix.llvm }} -Source winget -MatchOption Equals -Mode Silent -Force
        }
        clang --version
