on:
  push:
  pull_request:
  merge_group:
  schedule: # Trigger a job on default branch at 4AM PST everyday
    - cron: "0 11 * * *"

name: Local Development Makefile

env:
  RUSTFLAGS: -D warnings

jobs:
  build:
    name: Test WDR's local cargo-make Makefile
    strategy:
      fail-fast: false
      matrix:
        runner:
          - name: windows-latest
            arch: amd64
          - name: windows-11-arm
            arch: arm64

        wdk:
          - version: 10.0.22621 # NI WDK
            source: winget
          - version: 10.0.26100 # GE WDK
            source: nuget

        llvm:
          - 17.0.6

        # Exclude WDK 10.0.22621 with ARM64 runner as it doesn't ship certmgr and makecert binaries
        exclude:
          - runner:
              name: windows-11-arm
              arch: arm64
            wdk:
              version: 10.0.22621
              source: winget

    runs-on: ${{ matrix.runner.name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Winget
        uses: ./.github/actions/install-winget
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install LLVM ${{ matrix.llvm }}
        uses: ./.github/actions/install-llvm
        with:
          version: ${{ matrix.llvm }}

      - name: Install WDK (${{ matrix.wdk.version }})
        uses: ./.github/actions/install-wdk
        with:
          version: ${{ matrix.wdk.version }}
          source: ${{ matrix.wdk.source }}
          host: ${{ matrix.runner.arch }}
          target: ${{ matrix.runner.arch }}

      - name: Install Nightly Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Install Beta Rust Toolchain
        uses: dtolnay/rust-toolchain@beta
        with:
          components: clippy

      - name: Install Stable Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install Cargo Make
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make

      - name: Test wdk-pre-commit-flow cargo-make task
        run: cargo make wdk-pre-commit-flow
