name: Local Development Makefile

on:
  push:
  pull_request:
  merge_group:
  schedule: # Trigger a job on default branch at 4AM PST everyday
    - cron: "0 11 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  RUSTFLAGS: -D warnings

jobs:
  build:
    name: Test WDR's local cargo-make Makefile
    strategy:
      fail-fast: false # Allow all matrix variants to complete even if some fail
      matrix:
        runner:
          - name: windows-latest
            arch: x64
          - name: windows-11-arm
            arch: arm64

        wdk:
          - version: 10.0.22621 # NI WDK
            source: winget
          - version: 10.0.26100 # GE WDK
            source: nuget

        llvm:
          - 17.0.6

        target_triple:
          - name: x86_64-pc-windows-msvc
            arch: amd64
          - name: aarch64-pc-windows-msvc
            arch: arm64

    runs-on: ${{ matrix.runner.name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

        # - name: Install Winget
      #   uses: ./.github/actions/winget-install
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Winget
        run: |
          Install-Script winget-install -Force
          winget-install -Force

      - name: Install LLVM ${{ matrix.llvm }}
        run: |
          # Use native winget.exe instead of PowerShell module for ARM64 compatibility
          Write-Host "Checking for existing LLVM installation..."
          winget list --id LLVM.LLVM --exact --accept-source-agreements --disable-interactivity
          
          Write-Host "Force Installing LLVM ${{ matrix.llvm }}..."
          winget install --id LLVM.LLVM --version ${{ matrix.llvm }} --source winget --force --exact --silent --accept-source-agreements --accept-package-agreements --disable-interactivity
          
          if ($LASTEXITCODE -ne 0) {
            Write-Error "LLVM ${{ matrix.llvm }} force installation failed with exit code: $LASTEXITCODE"
            exit 1
          }

          clang --version

      - name: Install WDK (${{ matrix.wdk.version }})
        uses: ./.github/actions/install-wdk
        with:
          version: ${{ matrix.wdk.version }}
          source: ${{ matrix.wdk.source }}
          host: ${{ matrix.runner.arch }}
          target: ${{ matrix.target_triple.arch }}

      - name: Install Nightly Rust Toolchain (${{ matrix.target_triple.name }})
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
          targets: ${{ matrix.target_triple.name }}

      - name: Install Beta Rust Toolchain (${{ matrix.target_triple.name }})
        uses: dtolnay/rust-toolchain@beta
        with:
          components: clippy
          targets: ${{ matrix.target_triple.name }}

      - name: Install Stable Rust Toolchain (${{ matrix.target_triple.name }})
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: ${{ matrix.target_triple.name }}

      - name: Install Cargo Make
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make

      - name: Test wdk-pre-commit-flow cargo-make task
        run: cargo make wdk-pre-commit-flow
